### ISSUE TITLE
snapshots

### ISSUE THREAD

**Issue by shenbuguanni** [kjason/DnnNormTimeFreq4DoA#1]
您好，关于snapshots的问题想请教一下，在实际落地中，其中我们比较关注DOA的灵敏度的，论文中snapshots都是20起步，相当于计算协方差矩阵用的是20帧的信号计算的，这是非因果的，但是如果实际中采用当前帧+历史帧来计算的话，当遇到声源位置变化，协方差矩阵也是不稳定的，所以就此问题，论文中的方案有没有可能实现frame by frame的效果？

**Comment by kjason** [comment]
Thank you for your questions. You are free to run our methods with fewer snapshots and extend our Fig. 4 in the paper. However, robust estimation of spatial covariance matrices in a few-snapshot case is not the focus of the paper. Regarding the scenario where the sound source is moving, some tracking algorithms would be useful. If I understand your frame-by-frame question correctly, you may be interested in single-snapshot DoA estimation. It might be possible to extend the methods to the single-snapshot case. Although these are interesting questions but they fall outside the scope of the paper. Please feel free to let me know if you have more questions.
